#!/bin/bash
set -euo pipefail

install_server(){

  log "LOG" "VÉRIFICATION & INSTALLATION DU SERVEUR $ARK_SERVER_SERVICE SUR $HOSTNAME."
  if [[ -x "$ARK_SERVER_EXE_FILE" ]]; then
    log "OK" "LE SERVEUR $ARK_SERVER_SERVICE EST DÉJÀ INSTALLÉ DANS $ARK_SERVER_DIR SUR $HOSTNAME."
  else
    log "WARNING" "LE SERVEUR $ARK_SERVER_SERVICE N'EST INSTALLÉ DANS $ARK_SERVER_DIR SUR $HOSTNAME."
    log "LOG" "TÉLÉCHARGEMENT DU SERVEUR $ARK_SERVER_SERVICE AVEC APP ID $ARK_APP_ID DANS $ARK_SERVER_DIR SUR $HOSTNAME."
    if sudo -u "$USER_ACCOUNT" "$STEAM_CMD_EXE_FILE" +force_install_dir "$ARK_SERVER_DIR" +login anonymous +app_update "$ARK_APP_ID" validate +quit; then
      log "SUCCESS" "LE SERVEUR $ARK_SERVER_SERVICE A ÉTÉ INSTALLÉ DANS $ARK_SERVER_DIR SUR $HOSTNAME."
    else
      log "ERROR" "UNE ERREUR S'EST PRODUITE LORS DE L'INSTALLATION DU SERVEUR $ARK_SERVER_SERVICE DANS $ARK_SERVER_DIR SUR $HOSTNAME."
      log "DEBUG" "VEUILLEZ ESSAYER D'INSTALLER LE SERVEUR $ARK_SERVER_SERVICE MANUELLEMENT A L'AIDE DE LA COMMANDE SUIVANTE:"
      log "DEBUG" "sudo -u $USER_ACCOUNT $STEAM_CMD_EXE_FILE +force_install_dir $ARK_SERVER_DIR +login anonymous +app_update $ARK_APP_ID validate +quit"
      exit 1
    fi
  fi

}