#!/bin/bash
set -euo pipefail

user_manager_bashrc() {
  log "LOG" "VÉRIFICATION & AJOUT DE L'IMPORTATION DU SCRIPT DE MANAGEMENT DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT..."
  if grep -q "alias overseer=\"$OVERSEER_SCRIPT_FILE\"" "/home/$USER_ACCOUNT/.bashrc"; then
    log "OK" "L'IMPORTATION DU SCRIPT DE MANAGEMENT EST DÉJÀ PRÉSENTE DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT."
  else
    log "WARNING" "L'IMPORTATION DU SCRIPT DE MANAGEMENT EST MANQUANTE DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT."
    log "LOG" "AJOUT DE L'IMPORTATION DU SCRIPT DE MANAGEMENT DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT."
    # shellcheck source=/home/${USER_ACCOUNT}/.bashrc
    if echo "alias overseer=\"$OVERSEER_SCRIPT_FILE\"" >> "/home/$USER_ACCOUNT/.bashrc" && source "/home/$USER_ACCOUNT/.bashrc"; then
      log "SUCCESS" "L'IMPORTATION DU SCRIPT DE MANAGEMENT A ÉTÉ AJOUTÉE AVEC SUCCÈS DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT."
    else
      log "ERROR" "UNE ERREUR S'EST PRODUITE LORS DE L'AJOUT DE L'IMPORTATION DU SCRIPT DE MANAGEMENT DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT."
      log "DEBUG" "VEUILLEZ AJOUTER L'IMPORTATION DU SCRIPT DE MANAGEMENT DANS LE FICHIER .BASHRC DE L'UTILISATEUR $USER_ACCOUNT À L'AIDE DE LA COMMANDE SUIVANTE:"
      log "DEBUG" "echo 'alias overseer=\"$OVERSEER_SCRIPT_FILE\"' >> /home/$USER_ACCOUNT/.bashrc"
      exit 1
    fi
  fi
}

install_manager() {
  log "OVERSEER" "INSTALLATION DU GESTIONNAIRE DE SERVEURS OVERSEER DANS LE RÉPERTOIRE $OVERSEER_DIR."
  folder create "Overseer" "$OVERSEER_DIR" "755"
  folder copy "Scripts" "$CURRENT_DIR/scripts" "$OVERSEER_DIR"
  file copy "Configs" "$CURRENT_DIR/config" "$OVERSEER_DIR"
  file copy "Overseer Script" "$CURRENT_DIR/overseer.sh" "$OVERSEER_SCRIPT_FILE"
  permissions owner "Manager Folder" "$OVERSEER_DIR" "$USER_ACCOUNT"
  permissions executable "Overseer" "$OVERSEER_DIR/overseer.sh"
  user_manager_bashrc
  log "SUCCESS" "INSTALLATION DU GESTIONNAIRE DE SERVEURS OVERSEER RÉUSSIE."
}
