#!/bin/bash
set -euo pipefail

user_account_grant_sudo(){

  log "LOG" "VÉRIFICATION & AJOUT DE L'UTILISATEUR $USER_ACCOUNT AU GROUPE SUDO SUR $HOSTNAME."
  if groups "$USER_ACCOUNT" | grep "\bsudo\b" &>/dev/null; then
  log "OK" "L'UTILISATEUR $USER_ACCOUNT EST DÉJÀ DANS LE GROUPE SUDO SUR $HOSTNAME."
  else
    log "WARNING" "L'UTILISATEUR $USER_ACCOUNT N'EST PAS DANS LE GROUPE SUDO SUR $HOSTNAME."
    if sudo usermod -aG sudo "$USER_ACCOUNT"; then
      log "SUCCESS" "L'UTILISATEUR $USER_ACCOUNT A ÉTÉ AJOUTÉ AU GROUPE SUDO SUR $HOSTNAME."
    else
      log "ERROR" "UNE ERREUR S'EST PRODUITE LORS DE L'AJOUT DE $USER_ACCOUNT AU GROUPE SUDO SUR $HOSTNAME."
      log "DEBUG" "ESSAYEZ D'AJOUTER L'UTILISATEUR $USER_ACCOUNT AU GROUPE SUDO MANUELLEMENT A L'AIDE DE LA COMMANDE SUIVANTE:"
      log "DEBUG" "sudo usermod -aG sudo $USER_ACCOUNT"
      exit 1
    fi
  fi

}