#!/bin/bash
set -euo pipefail

user_account_cmd_no_pwd(){

  log "LOG" "VÉRIFICATION & PERMISSION DES COMMANDES SUDO SANS MOT DE PASSE POUR $USER_ACCOUNT SUR $HOSTNAME."
  if sudo grep -R "^$USER_ACCOUNT .*NOPASSWD:ALL" /etc/sudoers.d &>/dev/null; then
    log "OK" "L'UTILISATEUR $USER_ACCOUNT PEUT DÉJÀ ÉXÉCUTER DES COMMANDES SUDO SANS MOT DE PASSE SUR $HOSTNAME."
  else
    log "WARNING" "L'UTILISATEUR $USER_ACCOUNT NE PEUT PAS ÉXÉCUTER DES COMMANDES SUDO SANS MOT DE PASSE SUR $HOSTNAME."
    if echo "$USER_ACCOUNT ALL=(ALL) NOPASSWD:ALL" | sudo EDITOR='tee' visudo -f /etc/sudoers.d/"$USER_ACCOUNT"; then
      log "SUCCESS" "L'UTILISATEUR $USER_ACCOUNT PEUT MAINTENANT ÉXÉCUTER DES COMMANDES SUDO SANS MOT DE PASSE SUR $HOSTNAME."
    else
      log "ERROR" "UNE ERREUR S'EST PRODUITE LORS DE LA PERMISSION DES COMMANDES SUDO SANS MOT DE PASSE POUR $USER_ACCOUNT SUR $HOSTNAME."
      log "DEBUG" "VEUILLEZ ESSAYER DE PERMISSIONNER $USER_ACCOUNT POUR ÉXÉCUTER DES COMMANDES SUDO SANS MOT DE PASSE A L'AIDE DE LA COMMANDE SUIVANTE:"
      log "DEBUG" "echo \"$USER_ACCOUNT ALL=(ALL) NOPASSWD:ALL\" | sudo EDITOR='tee' visudo -f /etc/sudoers.d/$USER_ACCOUNT"
      exit 1
    fi
  fi

}